## Comment out when doing local development
backend:
  name: github
  repo: pauldoomgov/not-tts.gsa.gov
  base_url: https://pages.cloud.gov
  auth_endpoint: external/auth/github
  preview_context: pages/build
  branch: main
  use_graphql: true

# #
# # Uncomment when doing local development on Netlify CMS
# # Run `npx netlify-cms-proxy-server` to start working locally
# # In another terminal, start the app with `npm start`
# # See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# #

backend:
  name: git-gateway
local_backend: true

media_folder: _img
public_folder: _img
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Main Pages
    name: pages
    folder: pages/
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/page'}
      - {
        label: 'Page link',
        name: 'permalink',
        hint: "The URL this page will be accessible at.",
        pattern: ['^.*\/$', "Must end with a slash"],
        widget: 'string',
        default: '{{slug}}'}

      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Site Alert
    name: hero-alert
    create: false
    format: "json"
    files:
      - label: "Hero Alert"
        name: "hero-alert"
        file: "_data/heroAlert.json"
        fields:
          - {label: 'Message', name: 'message', widget: 'string'}
  - label: Join TTS Info Pages
    name: jointtspages
    folder: pages/jointts/
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/page'}
      - {
        label: 'Page link',
        name: 'permalink',
        hint: "The URL this page will be accessible at.",
        pattern: ['^.*\/$', "Must end with a slash"],
        widget: 'string',
        default: '{{slug}}'}

      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Services Page"
    name: Services
    create: true
    format: "yaml"
    files:
      - label: "Services"
        name: "services"
        file: "_data/services.yaml"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            label_singular: "service"
            order: "{{fields.name}}"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Link Alt Text, name: link_alt_text, widget: string}
              - {label: Logo, name: logo, widget: image}
              - {label: Logo Alt Text, name: logo_alt_text, widget: string}
              - {label: Category, name: category, widget: string}
              - {label: Description, name: description, widget: text}
