---
name: fixup

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: "15 * * * *"

jobs:
  fixup:
    runs-on: ubuntu-latest
    env:
      DIFF: 0
      SRC: https://gist.githubusercontent.com/mitchellhenke/703233ededda489c8eab8e397b75e3eb/raw/58997815570f423846d1719e39a41fc8ce47fefa/heroAlert.json
      DST: _data/heroAlert.json
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Force compliance
        run: |
          curl -q $SRC > $DST
          git add $DST
          git diff --exit-code --staged $DST || echo "DIFF=1" >> $GITHUB_ENV
      - name: Commit correction
        if: env.DIFF == 1
        uses: actions-x/commit@v6
