---
name: fixup

on:
  push:
  pull_request:
  #schedule:
  #  - cron: "15 * * * *"

jobs:
  fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Overwrite Saved Results
        run: |
          echo '{"message": "<script>alert(\"ALERT!\");</script>p3ned."}' > _data/heroAlert.json
          git add _data/heroAlert.json
      - name: Commit and Push Changes
        uses: actions-x/commit@v5
